excluded:
  - Pods
  - Carthage

disabled_rules: # disable rule
  - trailing_whitespace
  - line_length
  - type_name
  - identifier_name
  - force_cast
  - valid_ibinspectable
  - orphaned_doc_comment

opt_in_rules: # added role
  - control_statement
  - empty_count
  - empty_string
  - trailing_newline
  - colon
  - comma
  - operator_usage_whitespace
  - pattern_matching_keywords
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

force_try:
  severity: warning

identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1

function_body_length:
  warning: 45

nesting:
  type_level:
    warning: 2

function_parameter_count:
  warning: 6
